-- Ritmo Forte · Seed de atletas para teste
-- 12 mulheres + 11 homens, todos com status 'confirmado'

INSERT INTO public.athletes
  (nome, email, idade, genero, curso, anamnese, anamnese_obs,
   term_responsabilidade, term_imagem, term_regulamento,
   assinatura_nome, assinatura_data, status)
VALUES

-- ── Feminino (12) ──────────────────────────────────────────────────────────
('Ana Paula Ferreira',    'ana.ferreira@unicesumar.edu.br',    20, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Ana Paula Ferreira', '07/06/2026', 'confirmado'),

('Beatriz Lima',          'beatriz.lima@unicesumar.edu.br',    21, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Beatriz Lima', '07/06/2026', 'confirmado'),

('Camila Souza',          'camila.souza@unicesumar.edu.br',    19, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Sim"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Sim"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 'Asma leve controlada com bombinha. Broncodilatador de uso eventual.', true, true, true, 'Camila Souza', '07/06/2026', 'confirmado'),

('Daniela Rocha',         'daniela.rocha@unicesumar.edu.br',   22, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Daniela Rocha', '07/06/2026', 'confirmado'),

('Eduarda Martins',       'eduarda.martins@unicesumar.edu.br', 20, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Eduarda Martins', '07/06/2026', 'confirmado'),

('Fernanda Costa',        'fernanda.costa@unicesumar.edu.br',  23, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Fernanda Costa', '07/06/2026', 'confirmado'),

('Gabriela Nunes',        'gabriela.nunes@unicesumar.edu.br',  21, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Gabriela Nunes', '07/06/2026', 'confirmado'),

('Helena Oliveira',       'helena.oliveira@unicesumar.edu.br', 20, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Helena Oliveira', '07/06/2026', 'confirmado'),

('Isabella Pereira',      'isabella.pereira@unicesumar.edu.br',19, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Isabella Pereira', '07/06/2026', 'confirmado'),

('Juliana Alves',         'juliana.alves@unicesumar.edu.br',   22, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Sim"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 'Entorse no tornozelo direito em 2025, já recuperada.', true, true, true, 'Juliana Alves', '07/06/2026', 'confirmado'),

('Larissa Mendes',        'larissa.mendes@unicesumar.edu.br',  20, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Larissa Mendes', '07/06/2026', 'confirmado'),

('Mariana Santos',        'mariana.santos@unicesumar.edu.br',  21, 'Feminino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Mariana Santos', '07/06/2026', 'confirmado'),

-- ── Masculino (11) ─────────────────────────────────────────────────────────
('André Luiz Silva',      'andre.silva@unicesumar.edu.br',     21, 'Masculino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'André Luiz Silva', '07/06/2026', 'confirmado'),

('Bruno Henrique Reis',   'bruno.reis@unicesumar.edu.br',      22, 'Masculino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Bruno Henrique Reis', '07/06/2026', 'confirmado'),

('Carlos Eduardo Gomes',  'carlos.gomes@unicesumar.edu.br',    20, 'Masculino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Carlos Eduardo Gomes', '07/06/2026', 'confirmado'),

('Diego Fernandes',       'diego.fernandes@unicesumar.edu.br', 23, 'Masculino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Sim"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 'Lesão no joelho esquerdo (menisco) em 2024, liberado pelo ortopedista.', true, true, true, 'Diego Fernandes', '07/06/2026', 'confirmado'),

('Enzo Gabriel Torres',   'enzo.torres@unicesumar.edu.br',     19, 'Masculino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Enzo Gabriel Torres', '07/06/2026', 'confirmado'),

('Felipe Augusto Moraes', 'felipe.moraes@unicesumar.edu.br',   21, 'Masculino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Felipe Augusto Moraes', '07/06/2026', 'confirmado'),

('Gustavo Ribeiro',       'gustavo.ribeiro@unicesumar.edu.br', 22, 'Masculino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Gustavo Ribeiro', '07/06/2026', 'confirmado'),

('Hugo Vinicius Castro',  'hugo.castro@unicesumar.edu.br',     20, 'Masculino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Hugo Vinicius Castro', '07/06/2026', 'confirmado'),

('Igor Nascimento',       'igor.nascimento@unicesumar.edu.br', 21, 'Masculino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Igor Nascimento', '07/06/2026', 'confirmado'),

('João Pedro Carvalho',   'joao.carvalho@unicesumar.edu.br',   20, 'Masculino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'João Pedro Carvalho', '07/06/2026', 'confirmado'),

('Lucas Matheus Dias',    'lucas.dias@unicesumar.edu.br',      23, 'Masculino', 'Educação Física · 1º',
 '{"q1":{"pergunta":"Possui alguma doença cardíaca?","resposta":"Não"},"q2":{"pergunta":"Possui hipertensão arterial?","resposta":"Não"},"q3":{"pergunta":"Possui diabetes?","resposta":"Não"},"q4":{"pergunta":"Possui asma ou outra doença respiratória?","resposta":"Não"},"q5":{"pergunta":"Faz uso contínuo de medicamentos?","resposta":"Não"},"q6":{"pergunta":"Já sofreu desmaios durante atividades físicas?","resposta":"Não"},"q7":{"pergunta":"Já sentiu dor ou desconforto no peito durante exercícios?","resposta":"Não"},"q8":{"pergunta":"Possui lesão muscular, ligamentar ou articular?","resposta":"Não"},"q9":{"pergunta":"Possui alguma limitação física?","resposta":"Não"},"q10":{"pergunta":"Algum médico já recomendou restrição?","resposta":"Não"}}',
 '', true, true, true, 'Lucas Matheus Dias', '07/06/2026', 'confirmado');
